locale: 'se'
site_url: https://bleckert.se
logo_url: https://bleckert.se/assets/img/B_logo_big.png


backend:
  name: github
  repo: Janble2021/bleckert_se
  branch: main
  accept_roles:
    - admin
    - editor

# when using the default proxy server port
local_backend: True

media_folder: "/assets/blog_media"
public_folder: "/assets/blog_media"

publish_mode: editorial_workflow

collections:
  - label: "Blog posts"
    name: "Blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Titel"
        hint: "Titel till inlägget."
        name: "title"
        widget: "string"
      - label: "Bild"
        hint: "Miniatyrbild till inlägget."
        name: "image"
        widget: "image"
        required: false
      - label: "Kategori"
        hint: "Skriv in en ny eller befintlig kategori för att kategorisera inlägg. Kategorierna visas på webbplatsens startsida i vänstra panelen. Exempel 'Göta Kanal 2010'."
        name: "category"
        widget: "string"
        required: false
      - label: "Text"
        hint: "Inlägget skrivs i Markdown och har stöd för bland annat iframe."
        name: "body"
        widget: "markdown"
