backend:
  name: github
  repo: Janble2021/bleckert_se

  branch: main
  accept_roles:
    - admin
    - editor

# when using the default proxy server port
local_backend: True

media_folder: "/assets/blog_media"
public_folder: "/assets/blog_media"

publish_mode: editorial_workflow

collections:
  - label: "Blog posts"
    name: "Blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Bild"
        name: "image"
        widget: "image"
        required: false
      - label: "Rubrik"
        name: "title"
        widget: "string"
      - label: "Beskrivning"
        name: "description"
        widget: "text"
      - label: "Inlägg"
        name: "body"
        widget: "markdown"
